name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-12
    defaults:
      run:
        working-directory: ./projects/EssentialFeed

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.0.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Build and test macOS
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      - name: Build and test iOS 16
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.0,name=iPhone 12" ONLY_ACTIVE_ARCH=YES
